<?php
function mostrar_tabla_usuarios(){
    $html="";
    $sql="SELECT * FROM cuentas_usuario order by usuario";
    $result_usuarios=mysqli_query(conectar(),$sql);
    desconectar();
    $num=mysqli_num_rows($result_usuarios);
    if ($num>0){
        $i=0;
        $html.="<h4>Tabla de usuarios</h4>"; 
        $html.="<table id='tabla_usuarios' class='table.table-striped table-bordered table-hover table-condensed'>";
            $html.="<thead>";
                $html.="<tr>";
                    $html.="<th style='text-align:center'>#</th>";
                    $html.="<th style='text-align:center'>Usuario</th>";
                    $html.="<th style='text-align:center'>Contraseña</th>";
                    $html.="<th style='text-align:center'>Nombre</th>";
                    $html.="<th style='text-align:center'>Acciones</th>";
                $html.="</tr>";
            $html.="</thead>";
            $html.="<tbody>";
            while($col_usuarios=mysqli_fetch_array($result_usuarios)){
                $i+=1;
                $html.="<tr>";
                    $html.="<td style='text-align:center'>".$i."</td>";
                    $html.="<td><input disabled='disabled' class='form-control' name='input_usuario&".$i."' id='input_usuario&".$i."' value='".$col_usuarios['usuario']."'></input></td>";
                    $html.="<td><input disabled='disabled' class='form-control' name='input_password&".$i."' id='input_password&".$i."' value='".$col_usuarios['password']."'></input></td>";
                    $html.="<td><input disabled='disabled' class='form-control' name='input_nombre&".$i."' id='input_nombre&".$i."' value='".$col_usuarios['nombre']."'></input></td>";
                    $html.="<td>";
                        $html.="<button id='".$col_usuarios['id_usuario']."' onclick='editar_usuario(this.id);return false;'><span class='glyphicon glyphicon-edit' style='font-size:15px'></span></button>";
                        $html.="&nbsp;&nbsp;<button id='".$col_usuarios['id_usuario']."' onclick='actualizar_usuario(this.id);return false;'><span class='glyphicon glyphicon-floppy-saved' style='font-size:15px'></span></button>";
                        $html.="&nbsp;&nbsp;<button id='".$col_usuarios['id_usuario']."' onclick='eliminar_usuario(this.id);return false;'><span class='glyphicon glyphicon-trash' style='font-size:15px'></span></button>";
                    $html.="</td>";
                $html.="</tr>";
            }//Fin del while
            $html.="<input type='hidden' id='total_usuarios' name='total_usuarios' value='".$i."'>";
            $html.="</tbody>";    
            $html.="</table>";
    }//Fin del if..
    return $html;
}//fin de mostrar tabla usuarios

function mostrar_formato_cliente_vacio(){
    $html="";
    $html.='<div id="div_cliente" class="col-lg-12">';
        $html.='<div class="card">';
            $html.='<div class="card-body">';
                $html.='<h5 class="card-title">Datos del cliente</h5>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Nombre</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="nombre_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Pat</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="apellidopa_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Mat</label>';
                    $html.='<div class="col-sm-10">';
                    $html.='<input type="text" class="form-control" id="apellidoma_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Residencia</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="residencia_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Nacionalidad</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="nacionalidad_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputEmail" class="col-sm-2 col-form-label">Correo</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="email" class="form-control" id="correo_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputPassword" class="col-sm-2 col-form-label">Telefono</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="telefono_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Estado Civil</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="estadoc_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Actividad Económica</label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="act_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<div class="col-sm-9">';
                        $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_cliente();">Guardar Cliente</button>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        $html.='</div>';
    $html.='</div>';
    return $html;
}//fin de mostrar formato cliente vacio

function mostrar_formato_cliente($id_cliente){
    $html="";
    $sql="SELECT * from clientes where id_cliente LIKE '".$id_cliente."'";
    $result=mysqli_query(conectar(),$sql);
    desconectar();
    $num=mysqli_num_rows($result);
    if($num>0){
        while($col=mysqli_fetch_array($result)){
            $html.='<div id="div_cliente" class="col-lg-12">';
                $html.='<div class="card">';
                    $html.='<div class="card-body">';
                        $html.='<h5 class="card-title">Datos del cliente</h5>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Nombre</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="nombre_cliente" value="'.$col['nombre'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Pat</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="apellidopa_cliente" value="'.$col['apellido_paterno'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Mat</label>';
                            $html.='<div class="col-sm-10">';
                            $html.='<input type="text" class="form-control" id="apellidoma_cliente" value="'.$col['apellido_materno'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Residencia</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="residencia_cliente" value="'.$col['residencia'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Nacionalidad</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="nacionalidad_cliente" value="'.$col['nacionalidad'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputEmail" class="col-sm-2 col-form-label">Correo</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="email" class="form-control" id="correo_cliente" value="'.$col['correo'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputPassword" class="col-sm-2 col-form-label">Telefono</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="telefono_cliente" value="'.$col['telefono'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Estado Civil</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="estadoc_cliente" value="'.$col['estado_civil'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Actividad Económica</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="act_cliente" value="'.$col['act_economica'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label class="col-sm-2 col-form-label"></label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_cliente();">Guardar Contrato</button>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        }//fin del while
    }else{
        $html="";
    }//fin del else
    return $html;
}//fin de mostrar formato cliente vacio

function mostrar_formato_contrato_vacio(){
    $html="";
    $html.='<div id="div_contrato" class="col-lg-12">';
                $html.='<div class="card">';
                    $html.='<div class="card-body">';
                        $html.='<h5 class="card-title">Datos del contrato</h5>';
                        $html.='<input type="hidden" id="id_contrato" value="">';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha Contrato</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_contrato">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha firma</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_firma">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Precio de venta</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="precio_venta">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Tipo de compra</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" class="form-control" id="tipo_compra">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Cantidad Apartado</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="cant_apartado">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha apartado</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_apartado">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Cantidad enganche</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="cant_enganche">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha del enganche</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_enganche">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">No. de mensualidades</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="n_mensualidades">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Monto mensual</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="monto_mensual">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Pago final</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="pago_final">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Fase</label>';
                            $html.='<div class="col-sm-9">';
                                $html.=select_fase();
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div id="div_super_manzana" class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Super Manzana</label>';
                            $html.='<div id="div_select_super_manzana" class="col-sm-9">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div id="div_manzana" class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Manzana</label>';
                            $html.='<div id="div_select_manzana" class="col-sm-9">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div id="div_lote" class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Lotes Comprados</label>';
                            $html.='<div id="div_select_lote" class="col-sm-9">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<div class="col-sm-3" style="text-align:right;">';
                                $html.='<button type="button" id="btn_agregarResponsable" class="btn btn-success" onclick="agregar_lote()">+</button>&nbsp';
                                $html.='<button type="button" class="btn btn-warning" id="btn_quitarResposable" onclick="quitar_lote()">-</button>';
                            $html.='</div>';
                            $html.='<div class="col-sm-6">';
                                $html.='<textarea id="txtArea_lotes" disabled class="form-control"></textarea>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Estatus de la venta</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" class="form-control" id="estatus_venta">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Día de pago</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="dia_pago">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Nombre Descuento</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" class="form-control" id="nombre_descuento">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Tasa</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" id="tasa" class="form-control" onkeyup="validar_entrada(this.id)">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label class="col-sm-2 col-form-label"></label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_contrato();">Guardar Contrato</button>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
    return $html;
}//fin de mostrar formato contrato vacio

function mostrar_formato_contrato($id_contrato){
    $sql="SELECT * from contrato WHERE id_contrato LIKE '".$id_contrato."'";
    $result=mysqli_query(conectar(),$sql);
    $num=mysqli_num_rows($result);
    if($num>0){
        while($col=mysqli_fetch_array($result)){
            $html.='<div id="div_contrato" class="col-lg-12">';
                $html.='<div class="card">';
                    $html.='<div class="card-body">';
                        $html.='<h5 class="card-title">Datos del contrato</h5>';
                        $html.='<input type="hidden" id="id_contrato" value="">';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha Contrato</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_contrato" value="'.$col['fecha_contrato'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha firma</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_firma" value="'.$col['fecha_firma'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Precio de venta</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="precio_venta" value="'.$col['precio_venta'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Tipo de compra</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" class="form-control" id="tipo_compra" value="'.$col['id_tipo_compra'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Cantidad Apartado</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="cant_apartado" value="'.$col['cant_apartado'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha apartado</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_apartado" value="'.$col['fecha_apartado'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Cantidad enganche</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="cant_enganche" value="'.$col['cant_enganche'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Fecha del enganche</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="fecha_enganche" value="'.$col['fecha_enganche'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">No. de mensualidades</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="n_mensualidades" value="'.$col['mensualidades'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Monto mensual</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="monto_mensual" value="'.$col['monto_mensual'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Pago final</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="number" class="form-control" id="pago_final" value="'.$col['pago_final'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        //
                        $sql="SELECT * FROM ";
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Fase</label>';
                            $html.='<div class="col-sm-9">';
                                $html.=select_fase();
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div id="div_super_manzana" class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Super Manzana</label>';
                            $html.='<div id="div_select_super_manzana" class="col-sm-9">';
                            $html.=select_super_manzana($col['']);
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div id="div_manzana" class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Manzana</label>';
                            $html.='<div id="div_select_manzana" class="col-sm-9">';
                                $html.=select_fase();
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div id="div_lote" class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Lote</label>';
                            $html.='<div id="div_select_lote" class="col-sm-9">';
                                $html.=select_fase();
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Estatus de la venta</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" class="form-control" id="estatus_venta" value="'.$col['id_estatus_venta'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputDate" class="col-sm-3 col-form-label">Día de pago</label>';
                            $html.='<div class="col-sm-5">';
                                $html.='<input type="date" class="form-control" id="dia_pago" value="'.$col['dia_pago'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Nombre Descuento</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" class="form-control" id="nombre_descuento" value="'.$col['nombre_descuento'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-3 col-form-label">Tasa</label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<input type="text" id="tasa" class="form-control" onkeyup="validar_entrada(this.id)" value="'.$col['tasa'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label class="col-sm-2 col-form-label"></label>';
                            $html.='<div class="col-sm-9">';
                                $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_contrato();">Guardar Contrato</button>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        }//fin del while
    }else{

    }//fin del else
    return $html;
}//fin de mostrar formato contrato

function mostrar_tabla_contratos($id_cliente){
    $html="";
    $sql="SELECT c.id_cliente, co.id_contrato, co.fecha_contrato, lo.fase, lo.super_manzana, lo.mza, lo.lote from clientes as c inner join cliente_contrato as cc ON c.id_cliente = cc.id_cliente inner join contrato as co on cc.id_contrato = co.id_contrato inner join lotes_contrato as lc on co.id_contrato = lc.id_contrato inner join lotes as lo on lc.id_lote = lo.id_lote WHERE c.id_cliente LIKE '".$id_cliente."' order by co.id_contrato"; //Consultar id de la variable
    $result=mysqli_query(conectar(),$sql);
    desconectar();
    $num=mysqli_num_rows($result);
    if ($num>0){
        $i=1;
        $html.="<h4>Contratos del cliente</h4>"; 
        $html.="<table id='tabla_contratos' class='table.table-striped table-bordered table-hover table-condensed'>";
            $html.="<thead>";
                $html.="<tr>";
                    $html.="<th style='text-align:center'>#</th>";
                    $html.="<th style='text-align:center'>Lotes Comprados</th>";
                    $html.="<th style='text-align:center'>Fecha Contrato</th>";
                    $html.="<th style='text-align:center'>Acciones</th>";
                $html.="</tr>";
            $html.="</thead>";
            $html.="<tbody>";
            while($col=mysqli_fetch_array($result)){
                $html.="<tr>";
                    $html.="<td style='text-align:center'>".$i."</td>";
                    $html.="<td><input disabled='disabled' class='form-control' value='(".$col['fase']."-".$col['super_manzana']."-".$col['mza']."-".$col['lote'].")'></input></td>";
                    $html.="<td><input disabled='disabled' class='form-control' value='".$col['fecha_contrato']."'></input></td>";
                    //Botones para las acciones
                    $html.="<td>";
                        $html.="<button id='".$col['id_contrato']."' onclick='editar_contrato(this.id);'>Editar</button>";
                        $html.="&nbsp;&nbsp;<button id='".$col['id_contrato']."' onclick='eliminar_contrato(this.id);'>Eliminar</button>";
                    $html.="</td>";
                $html.="</tr>";
                $i++;
            }//Fin del while
            $html.="</tbody>";    
        $html.="</table>";
    }//Fin del if..
    return $html;
}//fin de mostrar tabla usuarios


?>