<?php
function mostrar_tabla_usuarios(){
    $html="";
    $sql="SELECT * FROM cuentas_usuario order by usuario";
    $result_usuarios=mysqli_query(conectar(),$sql);
    desconectar();
    $num=mysqli_num_rows($result_usuarios);
    if ($num>0){
        $i=0;
        $html.="<h4>Tabla de usuarios</h4>"; 
        $html.="<table id='tabla_usuarios' class='table.table-striped table-bordered table-hover table-condensed'>";
            $html.="<thead>";
                $html.="<tr>";
                    $html.="<th style='text-align:center'>#</th>";
                    $html.="<th style='text-align:center'>Usuario</th>";
                    $html.="<th style='text-align:center'>Contraseña</th>";
                    $html.="<th style='text-align:center'>Nombre</th>";
                    $html.="<th style='text-align:center'>Acciones</th>";
                $html.="</tr>";
            $html.="</thead>";
            $html.="<tbody>";
            while($col_usuarios=mysqli_fetch_array($result_usuarios)){
                $i+=1;
                $html.="<tr>";
                    $html.="<td style='text-align:center'>".$i."</td>";
                    $html.="<td><input disabled='disabled' class='form-control' name='input_usuario&".$i."' id='input_usuario&".$i."' value='".$col_usuarios['usuario']."'></input></td>";
                    $html.="<td><input disabled='disabled' class='form-control' name='input_password&".$i."' id='input_password&".$i."' value='".$col_usuarios['password']."'></input></td>";
                    $html.="<td><input disabled='disabled' class='form-control' name='input_nombre&".$i."' id='input_nombre&".$i."' value='".$col_usuarios['nombre']."'></input></td>";
                    $html.="<td>";
                        $html.="<button id='".$col_usuarios['id_usuario']."' onclick='editar_usuario(this.id);return false;'><span class='glyphicon glyphicon-edit' style='font-size:15px'></span></button>";
                        $html.="&nbsp;&nbsp;<button id='".$col_usuarios['id_usuario']."' onclick='actualizar_usuario(this.id);return false;'><span class='glyphicon glyphicon-floppy-saved' style='font-size:15px'></span></button>";
                        $html.="&nbsp;&nbsp;<button id='".$col_usuarios['id_usuario']."' onclick='eliminar_usuario(this.id);return false;'><span class='glyphicon glyphicon-trash' style='font-size:15px'></span></button>";
                    $html.="</td>";
                $html.="</tr>";
            }//Fin del while
            $html.="<input type='hidden' id='total_usuarios' name='total_usuarios' value='".$i."'>";
            $html.="</tbody>";    
            $html.="</table>";
    }//Fin del if..
    return $html;
}//fin de mostrar tabla usuarios

function mostrar_formato_cliente_vacio(){
    $html="";
    $html.='<div id="div_cliente" class="col-lg-12">';
        $html.='<div class="card">';
            $html.='<div class="card-body">';
                $html.='<h5 class="card-title">Datos del cliente</h5>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Nombre <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Nombre (s) del cliente"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="nombre_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Pat <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Apellido paterno del cliente"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="apellidopa_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Mat <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Apellido materno del cliente"></span></label>';
                    $html.='<div class="col-sm-10">';
                    $html.='<input type="text" class="form-control" id="apellidoma_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Residencia <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Lugar donde reside el cliente"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="residencia_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Nacionalidad <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Nación o territorio en el que vive el cliente"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="nacionalidad_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputEmail" class="col-sm-2 col-form-label">Correo <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Correo electrónico de contacto"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="email" class="form-control" id="correo_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputEmail" class="col-sm-2 col-form-label">Dirección <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Dirección del cliente"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="email" class="form-control" id="direccion_cliente" value="">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputPassword" class="col-sm-2 col-form-label">Telefono <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Teléfono de contacto"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="telefono_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Estado Civil <span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Situación de la persona determinada por sus relaciones de familia, provenientes del matrimonio o del parentesco"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="estadoc_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<label for="inputText" class="col-sm-2 col-form-label">Actividad Económica<span class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top" title="Labor o actividad a la que se dedica el cliente"></span></label>';
                    $html.='<div class="col-sm-10">';
                        $html.='<input type="text" class="form-control" id="act_cliente">';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-3">';
                    $html.='<div class="col-sm-9">';
                        $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_cliente();">Guardar Datos Cliente</button>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        $html.='</div>';
    $html.='</div>';
    return $html;
}//fin de mostrar formato cliente vacio

function mostrar_formato_cliente($id_cliente){
    $html="";
    $sql="SELECT * from clientes where id_cliente LIKE '".$id_cliente."'";
    $result=mysqli_query(conectar(),$sql);
    desconectar();
    $num=mysqli_num_rows($result);
    if($num>0){
        while($col=mysqli_fetch_array($result)){
            $html.='<div id="div_cliente" class="col-lg-12">';
                $html.='<div class="card">';
                    $html.='<div class="card-body">';
                        $html.='<h5 class="card-title">Datos del cliente</h5>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Nombre</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="nombre_cliente" value="'.$col['nombre'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Pat</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="apellidopa_cliente" value="'.$col['apellido_paterno'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Ape Mat</label>';
                            $html.='<div class="col-sm-10">';
                            $html.='<input type="text" class="form-control" id="apellidoma_cliente" value="'.$col['apellido_materno'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Residencia</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="residencia_cliente" value="'.$col['residencia'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Nacionalidad</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="nacionalidad_cliente" value="'.$col['nacionalidad'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputEmail" class="col-sm-2 col-form-label">Correo</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="email" class="form-control" id="correo_cliente" value="'.$col['correo'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputEmail" class="col-sm-2 col-form-label">Dirección</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="email" class="form-control" id="direccion_cliente" value="'.$col['direccion'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputPassword" class="col-sm-2 col-form-label">Telefono</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="telefono_cliente" value="'.$col['telefono'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Estado Civil</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="estadoc_cliente" value="'.$col['estado_civil'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<label for="inputText" class="col-sm-2 col-form-label">Actividad Económica</label>';
                            $html.='<div class="col-sm-10">';
                                $html.='<input type="text" class="form-control" id="act_cliente" value="'.$col['act_economica'].'">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-3">';
                            $html.='<div class="col-sm-9">';
                                $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_cliente();">Guardar Datos Cliente</button>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        }//fin del while
    }else{
        $html="";
    }//fin del else
    return $html;
}//fin de mostrar formato cliente vacio

function mostrar_formato_precontrato_vacio($input_cliente){
    $html="";
    $html.='<div id="div_precontrato" class="col-lg-12">';
        $html.='<div class="card">';
            $html.='<div class="card-body">';
                $html.='<h3 class="card-title">Datos de la Compra</h3>';
                $html.='<input type="hidden" id="id_contrato" value="'.$col['id_contrato'].'">';
                $html.='<div class="row mb-12">';
                    $html.='<p class="card-text">Descripci&oacuten de la Propiedad</p>';
                    $html.='<div class="col-sm-3">';
                        $html.='<label for="inputText" class="col-form-label">Fase</label>';
                    $html.='</div>';    
                    $html.='<div class="col-sm-3">';
                        $html.='<label for="inputText" class="col-form-label">Super Manzana</label>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<label for="inputText" class="col-form-label">Manzana</label>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<label for="inputText" class="col-form-label">Lote</label>';
                    $html.='</div>';
                $html.='</div>';
                $html.='<div class="row mb-12">';
                    $html.='<div class="col-sm-3">';
                        $html.=select_fase("");
                    $html.='</div>';
                    $html.='<div id="div_select_super_manzana" class="col-sm-3">';
                        $html.=select_super_manzana("", "");
                    $html.='</div>';
                    $html.='<div id="div_select_manzana" class="col-sm-3">';
                        $html.=select_manzana("", "", "");
                    $html.='</div>';
                    $html.='<div id="div_select_lote" class="col-sm-3">';
                        $html.=select_lotes("", "", "", "");
                    $html.='</div>';
                $html.='</div>';
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Tipo de compra</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Descuento Venta</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-5">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Descuentos</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.=select_tipo_compra("");
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="text" class="form-control" id="descuento_venta" name="descuento_venta" value="" disabled>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-5">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-8">';
                                $html.=select_descuentos();
                            $html.='</div>';
                            $html.='<div class="col-sm-4">';
                                $html.='<button type="button" id="btn_agregarResponsable" class="btn btn-success" onclick="agregar_descuento()">+</button>&nbsp';
                                $html.='<button type="button" class="btn btn-warning" id="btn_quitarResposable" onclick="quitar_descuento()">-</button>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<p class="card-text">Descuentos Aplicados</p>';
                    $html.='<div class="col-sm-6">';
                        $html.='<textarea id="desc_aplicados" name="desc_aplicados" class="form-control" disabled> </textarea>';
                    $html.='</div>';
                $html.='</div>';
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Precio de lista</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Precio Recomendado</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Precio de venta</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="precio_lista" value="" disabled>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="precio_recomendado" value="" disabled>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-md-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="precio_venta" value="" onblur="validar_precio_venta(this.id)" disabled>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<p class="card-text">Observaciones</p>';
                    $html.='<div class="col-sm-12">';
                        $html.='<textarea id="observaciones" class="form-control"></textarea>';
                    $html.='</div>';
                $html.='</div>';
                $html.='<hr>';
                $html.='<div class="row mb-12">';
                    $html.='<p class="card-text">Datos Apartado</p>';
                        $html.='<div class="col-sm-4">';
                            $html.='<div class="row">';
                                $html.='<div class="col-sm-12">';
                                    $html.='<label for="inputText" class="col-form-label">Cantidad Apartado</label>';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="col-sm-4">';
                            $html.='<div class="row">';
                                $html.='<div class="col-sm-12">';
                                    $html.='<label for="inputDate" class="col-form-label">Fecha pago apartado</label>';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="col-sm-4">';
                            $html.='<div class="row">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="col-sm-4">';
                            $html.='<div class="row">';
                                $html.='<div class="col-sm-12">';
                                    $html.='<input type="number" class="form-control" id="cant_apartado" value="">';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="col-sm-4">';
                            $html.='<div class="row">';
                                $html.='<div class="col-sm-12">';
                                    $html.='<input type="date" class="form-control" id="fecha_apartado" value="">';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="col-sm-4">';
                            $html.='<div class="row">';
                            $html.='</div>';
                        $html.='</div>';
                $html.='</div>';
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<p class="card-text">Datos Enganche</p>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Cantidad enganche</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputDate" class="col-form-label">Fecha pago enganche</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">N. Mensualidades Enganche</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Monto Mensual Enganche</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="cant_enganche" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="date" class="form-control" id="fecha_enganche" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="men_enganche" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="cant_mensual_enganche" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<p class="card-text">Datos de los pagos</p>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div id="div_n_mensualidades" class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">No. de mensualidades</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Monto mensual</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Pago final</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputDate" class="col-form-label">D&iacute;a primer pago</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div id="n_mensualidades" class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="n_mensualidades" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="monto_mensual" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="pago_final" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-3">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="date" class="form-control" id="dia_pago" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<div class="col-sm-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Monto Inter&eacutes(%)</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Nombre del Broker</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<label for="inputText" class="col-form-label">Comisi&oacuten Broker($)</label>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="tasa_interes" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="text" class="form-control" id="nombre_broker" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                    $html.='<div class="col-sm-4">';
                        $html.='<div class="row">';
                            $html.='<div class="col-sm-12">';
                                $html.='<input type="number" class="form-control" id="comision_broker" value="">';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
                /////
                $html.='<br>';
                $html.='<div class="row mb-12">';
                    $html.='<p class="card-text">Clientes</p>';
                    $html.='<div class="col-sm-4">';
                        $html.=select_clientes();
                    $html.='</div>';
                    $html.='<div class="col-sm-2">';
                        $html.='<button type="button" id="btn_agregarResponsable" class="btn btn-success" onclick="agregar_cliente()">+</button>&nbsp';
                        $html.='<button type="button" class="btn btn-warning" id="btn_quitarResposable" onclick="quitar_cliente()">-</button>';
                    $html.='</div>';
                    $html.='<div class="col-sm-6">';
                        $html.='<textarea id="txtArea_clientes" disabled class="form-control"></textarea>';
                    $html.='</div>';
                $html.='</div>'; 
                $html.='<br>';
                $html.='<div class="row mb-3">';
                    $html.='<div class="col-sm-12">';
                        $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_precontrato();">Guardar Datos Compra</button>&nbsp';
                        $html.='<button type="button" class="btn btn-secondary" onclick="cargar_datos_contrato();">Registrar datos contrato</button>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        $html.='</div>';
    $html.='</div>';
    return $html;
}//fin de mostrar formato precontrato

function mostrar_formato_precontrato($id_contrato){
    $html="";
    $sql="SELECT * from contrato where id_contrato LIKE '".$id_contrato."'";
    $result=mysqli_query(conectar(),$sql);
    desconectar();
    $num=mysqli_num_rows($result);
    if($num>0){
        while($col=mysqli_fetch_array($result)){
            $sql="SELECT fase, super_manzana, mza, lote, precio_lista FROM lotes where id_lote LIKE '".$col['id_lote']."'";
            //echo $sql;
            $resultado=mysqli_query(conectar(),$sql);
            desconectar();
            $num=mysqli_num_rows($resultado);
            if($num>0){
                $col_lotes = mysqli_fetch_array($resultado);
                $fase = $col_lotes['fase'];
                $super_manzana = $col_lotes['super_manzana'];
                $manzana = $col_lotes['mza'];
                $lote = $col_lotes['lote'];
                $precio_lista = $col_lotes['precio_lista'];
            }else{
                $fase = "";
                $super_manzana = "";
                $manzana = "";
                $lote = "";
                $precio_lista = "";
            }//fin del else
            $html.='<div id="div_precontrato" class="col-lg-12">';
                $html.='<div class="card">';
                    $html.='<div class="card-body">';
                        $html.='<h3 class="card-title">Datos de la Compra</h3>';
                        $html.='<input type="hidden" id="id_contrato" value="'.$col['id_contrato'].'">';
                        $html.='<div class="row mb-12">';
                            $html.='<p class="card-text">Descripci&oacuten de la Propiedad</p>';
                            $html.='<div class="col-sm-3">';
                                $html.='<label for="inputText" class="col-form-label">Fase</label>';
                            $html.='</div>';    
                            $html.='<div class="col-sm-3">';
                                $html.='<label for="inputText" class="col-form-label">Super Manzana</label>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<label for="inputText" class="col-form-label">Manzana</label>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<label for="inputText" class="col-form-label">Lote</label>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<div class="row mb-12">';
                            $html.='<div class="col-sm-3">';
                                $html.=select_fase($fase);
                            $html.='</div>';
                            $html.='<div id="div_select_super_manzana" class="col-sm-3">';
                                $html.=select_super_manzana($fase, $super_manzana);
                            $html.='</div>';
                            $html.='<div id="div_select_manzana" class="col-sm-3">';
                                $html.=select_manzana($super_manzana, $fase, $manzana);
                            $html.='</div>';
                            $html.='<div id="div_select_lote" class="col-sm-3">';
                                $html.=select_lotes($manzana, $super_manzana, $fase, $lote);
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Tipo de compra</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Descuento Venta</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-5">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Descuentos</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.=select_tipo_compra($col['id_tipo_compra']);
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $sql="SELECT tasa from cat_tipo_compra where id_tipo_compra LIKE '".$col['id_tipo_compra']."'";
                                        $resultado_tasa = mysqli_query(conectar(),$sql);
                                        desconectar();
                                        $num=mysqli_num_rows($resultado_tasa);
                                        if($num>0){
                                            $row = mysqli_fetch_array($resultado_tasa);
                                        }//fin del if
                                        $html.='<input type="number" class="form-control" id="descuento_venta" name="descuento_venta" value="'.$row[0].'" disabled>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-5">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-8">';
                                        $html.=select_descuentos();
                                    $html.='</div>';
                                    $html.='<div class="col-sm-4">';
                                        $html.='<button type="button" id="btn_agregarResponsable" class="btn btn-success" onclick="agregar_descuento()">+</button>&nbsp';
                                        $html.='<button type="button" class="btn btn-warning" id="btn_quitarResposable" onclick="quitar_descuento()">-</button>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<p class="card-text">Descuentos Aplicados</p>';
                            $html.='<div class="col-sm-6">';
                                $html.='<textarea id="desc_aplicados" name="desc_aplicados" class="form-control" disabled></textarea>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Precio de lista</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Precio Recomendado</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Precio de venta</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="precio_lista" value="'.$precio_lista.'" disabled>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="precio_recomendado" value="'.$precio_lista.'" disabled>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-md-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="precio_venta" value="'.$col['precio_venta'].'" onblur="validar_precio_venta(this.id)">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<p class="card-text">Observaciones</p>';
                            $html.='<div class="col-sm-12">';
                                $html.='<textarea id="observaciones" class="form-control">'.$col['observaciones'].'</textarea>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<hr>';
                        $html.='<div class="row mb-12">';
                            $html.='<p class="card-text">Datos Apartado</p>';
                                $html.='<div class="col-sm-4">';
                                    $html.='<div class="row">';
                                        $html.='<div class="col-sm-12">';
                                            $html.='<label for="inputText" class="col-form-label">Cantidad Apartado</label>';
                                        $html.='</div>';
                                    $html.='</div>';
                                $html.='</div>';
                                $html.='<div class="col-sm-4">';
                                    $html.='<div class="row">';
                                        $html.='<div class="col-sm-12">';
                                            $html.='<label for="inputDate" class="col-form-label">Fecha pago apartado</label>';
                                        $html.='</div>';
                                    $html.='</div>';
                                $html.='</div>';
                                $html.='<div class="col-sm-4">';
                                    $html.='<div class="row">';
                                    $html.='</div>';
                                $html.='</div>';
                                $html.='<div class="col-sm-4">';
                                    $html.='<div class="row">';
                                        $html.='<div class="col-sm-12">';
                                            $html.='<input type="number" class="form-control" id="cant_apartado" value="'.$col['cant_apartado'].'">';
                                        $html.='</div>';
                                    $html.='</div>';
                                $html.='</div>';
                                $html.='<div class="col-sm-4">';
                                    $html.='<div class="row">';
                                        $html.='<div class="col-sm-12">';
                                            $html.='<input type="date" class="form-control" id="fecha_apartado" value="'.$col['fecha_apartado'].'">';
                                        $html.='</div>';
                                    $html.='</div>';
                                $html.='</div>';
                                $html.='<div class="col-sm-4">';
                                    $html.='<div class="row">';
                                    $html.='</div>';
                                $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<p class="card-text">Datos Enganche</p>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Cantidad enganche</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputDate" class="col-form-label">Fecha pago enganche</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">N. Mensualidades Enganche</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Monto Mensual Enganche</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="cant_enganche" value="'.$col['cant_enganche'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="date" class="form-control" id="fecha_enganche" value="'.$col['fecha_enganche'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="men_enganche" value="'.$col['mensualidades_enganche'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="cant_mensual_enganche" value="'.$col['cant_mensual_enganche'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<p class="card-text">Datos de los pagos</p>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div id="div_n_mensualidades" class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">No. de mensualidades</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Monto mensual</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Pago final</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputDate" class="col-form-label">D&iacute;a primer pago</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div id="n_mensualidades" class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="n_mensualidades" value="'.$col['mensualidades'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="monto_mensual" value="'.$col['monto_mensual'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="pago_final" value="'.$col['pago_final'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="date" class="form-control" id="dia_pago" value="'.$col['dia_pago'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<div class="col-sm-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Monto Inter&eacutes(%)</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Nombre del Broker</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<label for="inputText" class="col-form-label">Comisi&oacuten Broker($)</label>';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="tasa_interes" value="'.$col['tasa_interes'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="text" class="form-control" id="nombre_broker" value="'.$col['nombre_broker'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                            $html.='<div class="col-sm-4">';
                                $html.='<div class="row">';
                                    $html.='<div class="col-sm-12">';
                                        $html.='<input type="number" class="form-control" id="comision_broker" value="'.$col['comision_broker'].'">';
                                    $html.='</div>';
                                $html.='</div>';
                            $html.='</div>';
                        $html.='</div>';
                        /////
                        $html.='<br>';
                        $html.='<div class="row mb-12">';
                            $html.='<p class="card-text">Clientes</p>';
                            $html.='<div class="col-sm-4">';
                                $html.=select_clientes();
                            $html.='</div>';
                            $html.='<div class="col-sm-2">';
                                $html.='<button type="button" id="btn_agregarResponsable" class="btn btn-success" onclick="agregar_cliente()">+</button>&nbsp';
                                $html.='<button type="button" class="btn btn-warning" id="btn_quitarResposable" onclick="quitar_cliente()">-</button>';
                            $html.='</div>';
                            $html.='<div class="col-sm-6">';
                                $html.='<textarea id="txtArea_clientes" disabled class="form-control">'.$col['clientes'].'</textarea>';
                            $html.='</div>';
                        $html.='</div>'; 
                        $html.='<br>';
                        $html.='<div class="row mb-3">';
                            $html.='<div class="col-sm-12">';
                                $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_precontrato();">Guardar Datos Compra</button>&nbsp';
                                $html.='<button type="button" class="btn btn-secondary" onclick="cargar_datos_contrato();">Registrar datos contrato</button>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        }//fin del while
    }else{
        $html="";
    }//fin del else
    return $html;
}//fin de mostrar formato precontrato

function mostrar_formato_contrato($id_contrato){
    $html="";
    $sql="SELECT * from contrato WHERE id_contrato LIKE '".$id_contrato."'";
    $result=mysqli_query(conectar(),$sql);
    $num=mysqli_num_rows($result);
    if($num>0){
        while($col=mysqli_fetch_array($result)){
            $html="";
            $html.='<div id="div_contrato" class="col-lg-12">';
                $html.='<div class="card">';
                    $html.='<div class="card-body">';
                        $html.='<h5 class="card-title">Datos del contrato</h5>';
                        $html.='<div class="row mb-12">';
                            $html.='<div class="col-sm-2">';
                            $html.='<label for="inputDate" class="col-form-label">Fecha Contrato</label>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                            $html.='<input type="date" class="form-control" id="fecha_contrato" value="'.$col['fecha_contrato'].'">';
                            $html.='</div>';
                            $html.='<div class="col-sm-1">';
                            $html.='</div>';
                            $html.='<div class="col-sm-2">';
                            $html.='<label for="inputDate" class="col-form-label">Fecha firma</label>';
                            $html.='</div>';
                            $html.='<div class="col-sm-3">';
                            $html.='<input type="date" class="form-control" id="fecha_firma" value="'.$col['fecha_firma'].'">';
                            $html.='</div>';
                            $html.='<div class="col-sm-1">';
                            $html.='</div>';
                        $html.='</div>';
                        $html.='<br>';
                        $html.='<div class="row mb-3">';
                            $html.='<div class="col-sm-9">';
                                $html.='<button type="button" class="btn btn-primary" onclick="guardar_datos_contrato();">Guardar Contrato</button>';
                            $html.='</div>';
                        $html.='</div>';
                    $html.='</div>';
                $html.='</div>';
            $html.='</div>';
        }//fin del while
    }//fin del if
    return $html;
}//fin de mostrar formato contrato

function mostrar_tabla_contratos($id_cliente){
    $html="";
    $sql="SELECT c.id_cliente, co.id_contrato, co.fecha_contrato, lo.fase, lo.super_manzana, lo.mza, lo.lote, ev.nombre from clientes as c inner join cliente_contrato as cc ON c.id_cliente = cc.id_cliente inner join contrato as co on cc.id_contrato = co.id_contrato inner join lotes as lo on co.id_lote = lo.id_lote inner join cat_estatus_venta as ev on co.id_estatus_venta = ev.id_estatus_venta WHERE c.id_cliente LIKE '".$id_cliente."' order by co.id_contrato"; //Consultar id de la variable
    $result=mysqli_query(conectar(),$sql);
    desconectar();
    $num=mysqli_num_rows($result);
    if ($num>0){
        $i=1;
        $html.='<h5 class="card-title">Contratos del Cliente</h5>';
        $html.="<table id='tabla_contratos' class='table table-responsive table-bordered table-striped table-hover table-condensed'>";
            $html.="<thead>";
                $html.="<tr>";
                    $html.="<th style='text-align:center'>#</th>";
                    $html.="<th style='text-align:center'>Lotes Comprados</th>";
                    $html.="<th style='text-align:center'>Estatus</th>";
                    $html.="<th style='text-align:center'>Acciones</th>";
                $html.="</tr>";
            $html.="</thead>";
            $html.="<tbody>";
            while($col=mysqli_fetch_array($result)){
                $html.="<tr>";
                    $html.="<td style='text-align:center'>".$i."</td>";
                    $html.="<td style='text-align:center'><input style='text-align:center' disabled='disabled' class='form-control' value='(".$col['fase']."-".$col['super_manzana']."-".$col['mza']."-".$col['lote'].")'></input></td>";
                    $html.="<td style='text-align:center'><input style='text-align:center' disabled='disabled' class='form-control' value='".$col['nombre']."'></input></td>";
                    //Botones para las acciones
                    $html.="<td style='text-align:center'>";
                        $html.="<button id='".$col['id_contrato']."' class='btn btn-sm btn-success' onclick='cargar_datos_precontrato(this.id);'>Editar</button>";
                        $html.="&nbsp;&nbsp;<button id='".$col['id_contrato']."' class='btn btn-sm btn-dark' onclick='eliminar_contrato(this.id);'>Eliminar</button>";
                    $html.="</td>";
                $html.="</tr>";
                $i++;
            }//Fin del while
            $html.="</tbody>";    
        $html.="</table>";
    }//Fin del if..
    return $html;
}//fin de mostrar tabla usuarios

function validar_datos_precontrato($id_contrato){
    $respuesta = "";
    $sql="SELECT fecha_enganche, cant_enganche FROM contrato where id_contrato LIKE '".$id_contrato."'";
    $result = mysqli_query(conectar(),$sql);
    desconectar();
    $num = mysqli_num_rows($result);
    if($num>0){
        $col = mysqli_fetch_array($result);
        $enganche = $col['cant_enganche'];
        $fecha_enganche = $col['fecha_enganche'];
        if($enganche!=0){
            $respuesta = "ok";
        }else{
            $respuesta = "error";
        }//fin del else
    }else{
        $respuesta = "error";
    }//fin del else
    return $respuesta;
}//fin de validar datos precontrato


?>